---
functional:
 - решение задачи на скорость против другого игрока. Оба игрока видят друг у друга редактор с кодом, вывод тестов, могут менять язык программирования во время решения
 - в игру можно играть с любым человеком, с ботом или другом (игра будет доступна по ссылке)
 - можно выбрать игру по уровню сложности. При создании игры можно выбрать определенную игру, иначе она будет подобрана наугад
 - задачи даны на двух языках — русском и английском
 - другие пользователи могут следить за ходом игры
 - в игре есть чат, в котором общаются зарегистрированные пользователи
 - завершенная игра доступна в записи. Редактор для ввода кода выглядит как проигрыватель
 - пользователи получают очки, на основе которых строится рейтинг за неделю, месяц и за все время
non-functional:
  - сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - сайт должен быть безопасным и защищать данные пользователя
  - сайт должен быть удобным на мобильном устройстве
  - сайт должен быть протестирован на совместимость с последними версиями браузеров
  - сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
    - не сохраняется язык программирования с прошлой игры
    - кнопка переключения отображения режима в чате соперника является избыточной
    - нет возможности выбрать смайлик в чате, в котором общаются зарегистрированные пользователи
